### PR TITLE
Improve widget and resolve issue #1 and #4

### PR DESCRIPTION
**Pull request by niiku**
Improve widget and resolve issue #1 and #4

- Rewrote the "Waypoints" in front.js so only one active heading is showing in the list. Used plain jQuery so the plugin "jquery.waypoints.js" could be removed.

Before:
image

After:
image

- Resolved issue #1. Background color and text of active list with wrapping are coherent. To get the real height I needed to add/remove a test element, because when wrapping occurs after setting the css-class 'active' the 'jQuery(..).height()' is still the old height.

Before:
image

After:
image

- Resolved issue #4. Now the previous heading after a certain offset is taken as the active one.

General question: What browser versions (especially IE) do you want to support?

### CODE REVIEW

**Comment by shazahm1** [comment]
Thanks for the pull! I look forward to testing it out. As far as browser support, the latest Chrome, Firefox, Edge plus IE11 is good enough.

**Comment by niiku** [comment]
Good to hear. I limited the JS syntax to ES5 and tested it in all 4 browsers. Let me know when you would like to have some modifications. 
Some more questions:
- I changed the behavior what the "active heading" is so only one is set as active. It's the first heading, or the closest one which is above the "Smooth Scroll Offset". Maybe this should be a separate configuration value like in [tocify the highlightOffset](http://gregfranko.com/jquery.tocify.js/#Options). Or was it desired from you that all visible headings are marked as active? 
- When clicking a link in the ez-toc-list and smooth scroll is on, I think the link should be set as active immediately after the click. Currently it's set as active after the scroll. What do you think?
- Would you mind to check in your IDE/codestyle configurations? So I can format the files easily the same way and generate the minified versions of .js/.css equals.

**Comment by okainov** [comment]
As for user for me #1 looks ugly, looking forward to have it merged and released soon!

**Comment by shazahm1** [comment]
@niiku 

**RE: Or was it desired from you that all visible headings are marked as active?**

The intent was to have all headings within the current viewport active.

**RE: When clicking a link in the ez-toc-list and smooth scroll is on, I think the link should be set as active immediately after the click. Currently it's set as active after the scroll. What do you think?**

I think it should be on scroll, so the TYOC items become active as they scroll into the viewport.

**RE: Would you mind to check in your IDE/codestyle configurations?**

Pull the editorconfig from this repo:

https://github.com/Connections-Business-Directory/Connections

**RE: generate the minified versions of .js/.css equals**

No need for you to generate. I have a grunt task setup to do this for me.

**Comment by niiku** [comment]
> The intent was to have all headings within the current viewport active.

Would you like to preserve this behavior? It's somewhat in contradiction to solve the issue #4.  
I would really prefere when only one heading is set as active, so should I make it configurable or do you dislike that?

> I think it should be on scroll, so the TYOC items become active as they scroll into the viewport.

Yes, I had it that way too. But when I click a link in the nav which is a bit further away from the current active one the active background goes for a millisecond to the clicked item, then it goes back to the previous, until it goes up/down as expected. Had this on different machines and different browsers (except in FF), also with the current released version. Do you experience this issue too? To make it less noisy I think it's more pleasant when the clicked link get's active before or after the scroll.

Thanks for the codestyle/grunt reference!

**Comment by niiku** [comment]
Can I do anything so that you're considering a merge of this pull? Just let me know what need to be changed

**Comment by shazahm1** [comment]
@niiku 

Sorry, this will very likely get merged. I just not have had the time to apply your changes on my test sight to review.

**Comment by KuroiMatoO** [comment]
It's possible to keep background untill next waypoint? I mean right now it only shows bg for items that visible on the screen. Dunno if it makes any sense, as example - https://advanced-js.github.io/syllabus/

**Comment by niiku** [comment]
@KuroiMatoO That's what I implemented in this pull too. Could you try my [fork](https://github.com/niiku/Easy-Table-of-Contents) and give me feedback if everything's working correctly? If you need assistance let me know.

**Comment by shazahm1** [comment]
Tested and merged :D

Thanks!!!

Here's the [download link to 2.0-rc2](https://github.com/shazahm1/Easy-Table-of-Contents/archive/2.0-rc2.zip).

**Comment by shazahm1** [comment]
@niiku 

Two items:

 1. Reported by a user; "*I see a strange bug in Safari on MacOS when using the affix option.  The sidebar is very bouncy/jittery when I scroll.  If I revert back to 1.7 the jitter stops.  I don't get the jitter on Firefox or Chrome on MacOS.*"
 2. Would it be possible for you to tweak sticky feature to work more like the TOC on this page? https://investorjunkie.com/8745/betterment-review/
They are using ezTOC with this jQuery plugin: https://github.com/garand/sticky and some JS to detect with the page/sidebar bottom is reached and unstick it.

Would you be willing to tackle these?

**Comment by niiku** [comment]
@shazahm1 Yes I can have a look. But do you have a Mac? I don't see a possibility to test this issue myself.

**Comment by shazahm1** [comment]
@niiku 

I have an iPad Pro I'm hoping I can test on. I can also ask the user to test too.

**Comment by shazahm1** [comment]
@niiku 

There seems to be a bug which causes the li.active item to grow in height as the pag is scrolled:

The is the style tag being added where the height is increased:

``` html
<style id="ez-toc-active-height">.ez-toc-widget-container ul.ez-toc-list li.active::before {height:2250px;} </style>
```

My guess it has to do with the workaround being used in the `getListElementHeightWithoutUlChildren()` function.

**Comment by shazahm1** [comment]
As a thought, I wonder if the adding/removing of that `li` is what is causing the jitter in Safari.

**Comment by niiku** [comment]
I'll search for an alternative. I knew this was a hack but I couldn't figure out a way to get the height before it was rendered :-/

**Pull request merged**
